<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Page Object test example" duration-ms="43421" started-at="2015-10-12T11:29:23Z" finished-at="2015-10-12T11:30:06Z">
    <groups>
    </groups>
    <test name="sample test" duration-ms="43421" started-at="2015-10-12T11:29:23Z" finished-at="2015-10-12T11:30:06Z">
      <class name="com.pp.tests.LoginPageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.pp.tests.LoginPageTest@5f7777ae]" name="setup" is-config="true" duration-ms="39813" started-at="2015-10-12T16:59:23Z" finished-at="2015-10-12T17:00:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyIamNewHereTestCase()[pri:0, instance:com.pp.tests.LoginPageTest@5f7777ae]" name="verifyIamNewHereTestCase" duration-ms="248" started-at="2015-10-12T17:00:03Z" finished-at="2015-10-12T17:00:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[I am New Here Text is Not Matching expected [I am ne here] but found [I am new here]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: I am New Here Text is Not Matching expected [I am ne here] but found [I am new here]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.pp.pages.LoginPage.getIamNewHereText(LoginPage.java:98)
	at com.pp.tests.LoginPageTest.verifyIamNewHereTestCase(LoginPageTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyIamNewHereTestCase -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.pp.tests.LoginPageTest@5f7777ae]" name="tearDown" is-config="true" duration-ms="3318" started-at="2015-10-12T17:00:03Z" finished-at="2015-10-12T17:00:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.pp.tests.LoginPageTest -->
    </test> <!-- sample test -->
  </suite> <!-- Page Object test example -->
</testng-results>
