<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="QSIH-00268" name="com.pp.tests.LoginPageTest" tests="6" failures="1" timestamp="15 Dec 2015 10:59:42 GMT" time="55.436" errors="0">
  <testcase name="clickOnLoginWithvalidUsernameAndInvalidPasswordAndVerifyWarningMessage" time="26.950" classname="com.pp.tests.LoginPageTest">
    <failure type="java.lang.AssertionError" message="Warning Message Text is Missing expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Warning Message Text is Missing expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.pp.pages.LoginPage.verifyWarningMessageHeader(LoginPage.java:466)
	at com.pp.tests.LoginPageTest.clickOnLoginWithvalidUsernameAndInvalidPasswordAndVerifyWarningMessage(LoginPageTest.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- clickOnLoginWithvalidUsernameAndInvalidPasswordAndVerifyWarningMessage -->
  <testcase name="verifyIamNewHereTestCase" time="3.566" classname="com.pp.tests.LoginPageTest"/>
  <testcase name="clickOnNeedHelpWithyourUsernamePassLink" time="4.000" classname="com.pp.tests.LoginPageTest"/>
  <testcase name="verifyAllReadyMembersElements" time="0.057" classname="com.pp.tests.LoginPageTest"/>
  <testcase name="clickOnLoginWithInvalidUsernameAndPassword" time="9.602" classname="com.pp.tests.LoginPageTest"/>
  <testcase name="clickOnLoginWithValidCredentials" time="11.261" classname="com.pp.tests.LoginPageTest"/>
</testsuite> <!-- com.pp.tests.LoginPageTest -->
